
apiVersion: v1
kind: Pod 
metadata: 
  name: prodpod
  namespace: dev
  labels:   
    app: myapp 
spec: 
    containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort : 80
              protocol : TCP
              name: nginx
--- 
apiVersion: v1 
kind: Service
metadata:
    name: b24service
    namespace: dev 
spec: 
    type: NodePort
    selector: 
      app: myapp
    ports: 
        - port: 80 
          targetPort: 80
          protocol: TCP 
    
